name: Production

on:
  workflow_dispatch:

jobs:


  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: cd modules/documentation && mkdocs gh-deploy --force && cd ../..

  utils:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-utils

  contracts:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-contracts

  protocol:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-protocol

  engine:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-engine

  server-node:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-server-node

  browser-node:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-browser-node

  router:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make test-router

  messaging:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: make pull-latest
      - run: make messaging
      - run: make start-messaging
      - run: make test-messaging
      - name: Print logs
        if: failure()
        run: docker service logs --tail 200 messaging_auth
          '
